name:                h3layer
version:             0.1.0.0
github:              "https://github.com/debasishg/hask"
license:             BSD3
author:              "Debasish Ghosh"
maintainer:          "dghosh@acm.org"
copyright:           "2020 Debasish Ghosh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/h3layer#readme>

# dependencies:
# - base >= 4.7 && < 5

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - OverloadedLabels
  - RecordWildCards
  - ScopedTypeVariables
  - TypeApplications
  - TypeFamilies
  - TypeOperators

library:
  source-dirs: src

  exposed-modules:
    - Prelude
    - Lib
    - Lib.App
    - Lib.App.Env
    - Lib.App.Error
    - Lib.App.Monad
    - Lib.Effects.Log
    - Lib.Config
    - Lib.Core.Account
    - Lib.Core.Email
    - Lib.Core.Id
    - Lib.Core.Password
    - Lib.Core.Transaction
    - Lib.Core.User
    - Lib.Db
    - Lib.Db.Functions
    - Lib.Db.Schema
    - Lib.Repository
    - Lib.Repository.Account
    - Lib.Repository.AccountRepo
    - Lib.Repository.Transaction
    - Lib.Repository.TransactionRepo
    - Lib.Repository.User
    - Lib.Repository.UserRepo
    - Lib.Service
    - Lib.Service.Account
    - Lib.Service.AccountService

  dependencies:
    - base-noprelude 
    - relude 
    - resource-pool
    - postgresql-simple 
    - postgresql-simple-named 
    - co-log 
    - mtl 
    - text
    - bytestring
    - lens
    - proto-lens
    - proto-lens-protoc
    - proto-lens-runtime
    - aeson
    - bcrypt
    - tomland
    - say
    - time
    - safe-money
    - stm
    - lifted-async

  ghc-options: 
    - -Wall 
    - -Wincomplete-uni-patterns 
    - -Wincomplete-record-updates 
    - -Wcompat 
    - -Widentities 
    - -Wredundant-constraints 
    - -fhide-source-paths 
    - -Wpartial-fields

executables:
  h3layer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - h3layer
    - base-noprelude

tests:
  h3layer-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
      - h3layer
      - base-noprelude
      - hspec 
      - hspec-core
      - hspec-expectations
      - relude 
      - text
      - mtl
      - time
